### ISSUE TITLE
无法生效，请求查看器显示script abort

### ISSUE THREAD

**Issue by baker221** [wibus-wee/activation-script#36]
### Describe the bug

我只想使用pro的更改主题功能。我在一台腾讯云服务器上用docker部署了该服务。然后把activator.js 的127.0.0.1换成了我机器的IP，但是依然无法生效。

Surge配置页面：
<img width="780" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/43471538/78dfeb44-f227-4d80-b7a8-a2ebb3941787">

Surge请求查看器结果：
![image](https://github.com/wibus-wee/raycast-unblock/assets/43471538/d75463c2-493a-40ed-bdae-96163be2305c)

### Reproduction

1 远端docker部署 2 surge mitm打开 3 不能使用

### System Info

```Shell
mac m2 Monterey 12.6.7
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
尝试一下实时构建的activator吧😂

**Comment by wibus-wee** [comment]
有一个新功能没发布在 v1.6.0 的 release 里：https://github.com/wibus-wee/activation-script/commit/b3dd72af6b48e47831560926155c9acaf3225ba1

要不然估计会容易调查出问题一点...

**Comment by wibus-wee** [comment]
啊是的...因为我想着减小包大小所以变成这样了..

你去实际用一下？ 这个surge的脚本编辑器里的执行看不出来啥

**Comment by wibus-wee** [comment]
哇 我破防了

你先用着 rewrite header吧...😂 我放假看看什么问题

**Comment by wibus-wee** [comment]
我看了一下，我怎么觉得你这脚本有点问题呢？

因为正常情况下，在Surge脚本编辑器里面点击执行按钮，会出现类似于这样的结果：

![CleanShot 2024-04-04 at 07 36 40@2x](https://github.com/wibus-wee/activation-script/assets/62133302/455762ac-d893-409f-929e-eeb9f1596b21)

你提供的截图中完全没有 Log，但是你的surge配置中又已经把调试模式开启了，所以不会是 log 被隐藏的问题

**Comment by wibus-wee** [comment]
非常奇怪🤔 有可能吧...我没法解决这个问题🥺🥺

**Comment by wibus-wee** [comment]
啊 这个是我的脚本历史遗留问题..

需要把 /me 接口的 func 改为unblockRequest...

总之就是很麻烦就是了...您还是不要搞这个了😂

rewrite header 是正解

**Comment by wibus-wee** [comment]
无论是哪种方式 只要raycast的请求无法被拦截修改，就不可以了

按照你的问题来回答的话，是的，rewrite 和 script 都需要启动代理的情况下才有效

另外，关于ai的问题，你能移步至 raycast unblock 仓库再次创建新 issue 来解决这个问题吗？ 另外给出错误日志，感谢理解🙏

**Comment by wibus-wee** [comment]
我这里看到似乎是你的配置文件路径问题？

你可能需要指定的是： ./config/config.toml

**Comment by ljh740** [comment]
> > 我这里看到似乎是你的配置文件路径问题？
> > 你可能需要指定的是： ./config/config.toml
> 
> 修改后正常了，感谢

可以分享下服务器吗 懒得自建哈哈哈

**Comment by ljh740** [comment]
> > > > 我这里看到似乎是你的配置文件路径问题？
> > > > 你可能需要指定的是： ./config/config.toml
> > > 
> > > 
> > > 修改后正常了，感谢
> > 
> > 
> > 可以分享下服务器吗 懒得自建哈哈哈
> 
> 不可以，用了自己的gpt api key

我只想解锁pro，可以保证不适用AI。或者能不能阉割下开一个独立解锁的端口出来。

**Comment by wibus-wee** [comment]
直接使用本项目可以解锁 pro 的，不需要第三方服务

**Comment by zhuozhiyongde** [comment]
> > > > 我这里看到似乎是你的配置文件路径问题？
> > > > 你可能需要指定的是： ./config/config.toml
> > > 
> > > 
> > > 修改后正常了，感谢
> > 
> > 
> > 可以分享下服务器吗 懒得自建哈哈哈
> 
> 不可以，用了自己的gpt api key

你可以试试 https://arthals.ink/posts/coding/unlocking-raycast-with-surge，用 FastAPI 后端 + Surge 改写的脚本就行。

> 逮住维护过刷课机的校友（什

**Comment by ljh740** [comment]
> 直接使用本项目（activation-script）可以解锁 pro 的，不需要第三方服务


Events
23:44:50.297945 [Connection] Incoming proxy protocol: HTTP
23:44:50.298314 [Script] HTTP request script found: raycast-me/trial_status-backend.raycast.com
23:44:50.299216 [Connection] Disconnect with reason: Script abort
直接使用看起来没有成功

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Aengelus, @wtzb, @narisada014, @WiseChannel, @technologyinvestor, @mhz987, @geoffwellman, @richardjypark, @liuderchi, @6boris, @iAMNABHON, @luis-herasme, @dozortsev, @gokhansa, @itskhanow, @johnexzy, @leodsoft, @chenbimo, @pkuhonker, @hhh2012aa, @mvpotter, @intellectb, @aurda012, @voith, @jasoncui, @TicTacWeb3, @2pai, @DouglasPimentel, @zsxueyuan, @PoliZyh, @kangshuisheng, @Harnek, @WillianLiusHao, @Kabie, @minyangcheng, @pi-ka, @nekofar, @frkcn, @bankel, @0rhan, @linkinzhiyuan, @ziyacan, @shengzhc, @criticalbh, @xxlv, @zhanba, @Shouperman, @Hokid, @blipn, @xianshuiAceysx, @wantzjt-zz, @yorusiku, @MehranMazhar, @shawnmoyer, @okwme, @neryajanel, @xitong-0629, @drkchain, @TheRealFREDP3D, @nelreina, @tranhan66, @goldcatglass, @joyceczy, @kyuiki, @julianclatro, @linfui, @thomasschulze, @Lengso, @viczhangge, @KhanUbel, @html-krit, @alpha0-dev, @jmmanos, @haimenlinchen, @ro2lfish, @lubarskyy, @eliseumds, @luo9527k, @anhgeeky, @shahradelahi, @h0ngcha0, @eizyc66, @zbndm, @huruji, @mtxmzkqlhc, @varinliali, @mster, @ouxch, @silviu-dima, @jeremyfn, @yofine, @adamrhunter, @escottalexander, @gabrielAnzaldo, @memorylane80, @jarvisaoieong, @zhouzhuhao, @t83714, @woheV6DouglasPimentel, @DanielXuuuuu, @apianmuse, @AmorDiamond, @AlexGuG3, @Aizener, @iFwu, @vishal423, @nilslice, @shenbomo, @awaqit, @PeterL328, @xiezipei, @Mintnoii, @perterest, @billy1624, @vcluopeng, @Deepcryptodive, @transmissions11, @erik-iglikov, @xzw, @shangsinian, @creaux, @panda8z, @haorui, @mary-lilypad, @colindog, @linkinzhiyuan, @0x7An, @yedy99, @leighayanid, @zhangv, @PatMyron, @ibigbug, @alihanayaz, @shengzhc, @iurimatias, @zeyuyuan, @MarkSr33, @cjpatoilo, @nicksarafa, @adnasa, @leemz2016, @Yorgg, @SINeWang, @eligrey, @Ken-Sinn, @chris-aeviator, @hzhlqp, @zlanchunEvgeneOskin, @levi0913, @9iks, @PilotDebug, @Vdan123, @raythunder, @malexanderlvz, @KeanuPang, @hubeen, @jbpionnier, @JoeyKo, @ahy231, @danielpza, @comminco, @mchinaloy, @ACollectionOfAtoms, @inscore, @TomatoSoup0126, @crtlib, @th3n3rd, @mahad53, @LiJiakai, @istiyakamin, @foreachsky, @ersingencturk, @zachary-horvath, @cooaer, @channg, @BellaHao, @BaNgZ5513, @xiaose009, @18039514772, @noman-land, @maulik-p, @Halokitiboy, @johntran, @NicholasJarr, @KingNNT, @kekewind, @tutq8118, @vdcat, @matborowiak, @saeed-junaid, @ralyodio, @SimonDeve, @josempineiro, @Manviel, @iliaskarim, @justrdk, @bdbabiakbagoesz21, @smallg, @pearone, @0a00ez, @q13, @kioqq, @tylerbuchea, @leeroydon1994, @rafialhamd, @anyhong, @marcbarany, @gazjessep, @afc163, @TranVanKung, @yowinon, @dianpeng, @Lisayg, @casperhale, @batmatt79, @BenjaminRCooper, @NicholasJarr, @jdcas89, @usernamex, @nickzyang, @yushimatenjin, @Karl10086, @kalyskhairy, @phylantrop, @KlotzAndrew, @Ella77, @mortezakarimi, @alexsicart, @ashfordbarstow, @yxping, @AlexanderFSP, @dominikschubert, @hechen0, @Cleomir, @xmxvii, @jimcal, @SejunRyu, @diego-G, @oscar-liu, @MaiJiantian, @RamirezJA, @jerod2000, @Sagarshrestha12, @maidh91, @lvzhenbang, @matt-ramotar
