### ISSUE TITLE
无法生效，请求查看器显示script abort

### ISSUE THREAD

**Issue by ljh740** [wibus-wee/activation-script#41]
### Describe the bug

我只想使用pro的更改主题功能。

Events
23:44:50.297945 [Connection] Incoming proxy protocol: HTTP
23:44:50.298314 [Script] HTTP request script found: raycast-me/trial_status-backend.raycast.com
23:44:50.299216 [Connection] Disconnect with reason: Script abort
直接使用看起来没有成功
GitHub Action 💥 Latest
GitHub Release 📦 Stable
都试过了

### Reproduction

https://github.com/wibus-wee/activation-script/raw/gh-pages/activator.sgmodule

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 37.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ljh740** [comment]
> 你能像 #36 那样复现一下请求相关域名时你的 surge 日志吗？

完整日志:
```
Rule Evaluating - ≤ 1 ms
Establishing TCP Connection - 46 ms
Script Evaluating - 2 ms
Active - 710 ms

Events
00:05:02.885972 [Connection] Incoming proxy protocol: HTTP
00:05:02.886583 [Rule] Rule evaluating requires DNS lookup for rule: IP-CIDR 152.67.219.74/32
00:05:02.886701 [Rule] DNS completed in 0.08ms, IPv4 address for matching: 18.66.112.113, IPv6 address for matching: 2600:9000:215a:9400:16:ea0d:cb00:93a1
00:05:02.887803 [Rule] Rule matched: FINAL
00:05:02.887923 [Rule] Policy decision path: ✈️ 节点选择 -> 🇭🇰 香港节点 -> 🇭🇰 HK丨Hong Kong 01
00:05:02.888193 [Script] HTTP response script found: raycast-activate-backend.raycast.com
00:05:02.888596 [Socket] Use the last successful address: 117.149.198.47
00:05:02.889027 [Socket] Connecting with address: 117.149.198.47, bound to the primary interface (en0) explicitly under Enhanced Mode, use TCP Fast Open
00:05:02.936060 [Socket] Connected to address 117.149.198.47 in 46ms
00:05:02.936111 [Socket] Attempted to use TCP Fast Open but failed (tfo_heuristics_disable)
00:05:02.936170 [Connector] TCP connection established
00:05:03.069299 [TLS] TLS handshake completed, negotiated cipher: TLS_AES_128_GCM_SHA256, protocol TLSv1.3
00:05:03.645330 [Script] Script failed, abort.
00:05:03.646676 [Connection] Disconnect with reason: Script abort
```

**Comment by wibus-wee** [comment]
我需要 surge 运行日志，不是这个请求日志😂

他在通用设置里面

**Comment by ljh740** [comment]
> 我需要 surge 运行日志，不是这个请求日志😂
> 
> 他在通用设置里面


2024-04-19 00:09:56.827111 <WARNING> [SGExternalResource] Failed to load resource from cache: https://github.com/wibus-wee/activation-script/raw/gh-pages/activator.js
2024-04-19 00:09:56.827501 <WARNING> [SGJSVM] Failed to load script: https://github.com/wibus-wee/activation-script/raw/gh-pages/activator.js, (null)

我手动访问https://github.com/wibus-wee/activation-script/raw/gh-pages/activator.js 以后 突然可以了 懵逼。。大概是你这写法不太对  要用https://raw.githubusercontent.com/wibus-wee/activation-script/gh-pages/activator.js

**Comment by wibus-wee** [comment]
raw path会跳转到对应的asset url的.. surge 会自行处理跳转

你确定你有点击更新外部资源按钮么？

**Comment by ljh740** [comment]
> raw path会跳转到对应的asset url的.. surge 会自行处理跳转
> 
> 你确定你有点击更新外部资源按钮么？

必须点了 除了手动在浏览器访问这个地址外 没有其他操作

**Comment by wibus-wee** [comment]
那其实挺奇怪🤔 我一直也是这么用的

我有时间改下url吧
